version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  test:
    docker:
      - image: cimg/node:18.4.0
    working_directory: ~/react-slingshot
    steps:
      - checkout
      - run: npm run test
  analyse:
    docker:
      - image: cimg/node:18.4.0
    working_directory: ~/react-slingshot
    steps:
      - checkout
      - run: npm analyse

workflows:
  my-workflow:
    jobs:
      - build
      - test:
          requires: 
            - build
      - analyse:
          requires:
            - test